[package]
name = "makepty"
version = "0.1.0"
authors = ["Thomas van der Berg <ik@thomasvanderberg.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
portable-pty = "0.4.0"
anyhow = "1.0.40"
